# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test package

on:
  [workflow_dispatch]
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox tox-gh-actions pre-commit
    - name: Run pre-commit on all files
      run: |
        pre-commit run --all-files
    - name: Create env file
      run: |
        touch .env
        echo FEDERATION_URL=${{ secrets.FEDERATION_URL }} >> .env
        echo API_KEY=${{ secrets.API_KEY }} >> .env
        echo MM_API_KEY=${{ secrets.MM_API_KEY }} >> .env
        echo FABRIC=$${{ secrets.FABRIC }} >> .env
        cat .env
    - name: Test with tox
      run: tox
    - name: Test markdown files links
      run: |
        python tests/url_tester.py
